[package]
name = "goku"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2-sys = "0.34.5"
nalgebra = "0.32.2"
imgui = { version = "0.11.0", features = ["docking"] }
imgui-glow-renderer = "0.11.0" 
imgui-sdl2-support = "0.11.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_derive = "1.0.163"
rfd = "0.11.3"
rand = "0.8.5"
glow = "0.12.2"
webbrowser = "0.8.11"
chrono = "0.4.31"
clipboard = "0.5.0"

[dependencies.sdl2]
version = "0.34"
default-features = false
features = ["image", "ttf", "mixer"]

[dependencies.gl]
git = "https://github.com/bjz/gl-rs"